import re
with open('services/meet-signal/main_test.go', 'r', encoding='utf-8') as f: content = f.read()
content = re.sub(r'\"io\"\n', '', content)
content = re.sub(r'wsURLMismatch :=', 'hdrMismatch := http.Header{"Sec-WebSocket-Protocol": {"meet-token, " + respLK.Token}}\n\twsURLMismatch :=', content)
content = re.sub(r'wsURLNoToken :=', 'hdrNoToken := http.Header{}\n\twsURLNoToken :=', content)
content = re.sub(r'wsURLMixed :=', 'hdrMixed := http.Header{"Sec-WebSocket-Protocol": {"meet-token, " + respLK.Token}}\n\twsURLMixed :=', content)
content = re.sub(r'wsURLConflict :=', 'hdrConflict := http.Header{"Sec-WebSocket-Protocol": {"meet-token, " + targetResp.Token}}\n\twsURLConflict :=', content)
content = re.sub(r'wsURLTarget :=', 'hdrTarget := http.Header{"Sec-WebSocket-Protocol": {"meet-token, " + targetResp.Token}}\n\twsURLTarget :=', content)
content = re.sub(r'wsURLGuest :=', 'hdrGuest := http.Header{"Sec-WebSocket-Protocol": {"meet-token, " + guestResp.Token}}\n\twsURLGuest :=', content)
with open('services/meet-signal/main_test.go', 'w', encoding='utf-8') as f: f.write(content)
