[package]
name = "wasm-sframe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
wasm-bindgen = "0.2"
sframe = { version = "0.3", features = ["wasm"] }
aes-gcm = "0.10"
ctr = "0.9"
getrandom = { version = "0.2", features = ["js"] }
sha2 = "0.10"
zeroize = "1.7"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace]